/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.TowarModel;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author andrz
 */
public class TowarView extends javax.swing.JFrame {
    private List<TowarModel> items;
    public List<TowarModel> getItems() {
        return items;
    }

    public void setItems(List<TowarModel> items) {
        this.items = items;
    }

    public int getSelectedItemIndexInt() {
        return Integer.parseInt(SelectedItemIndex.getText()) - 1;
    }

    public void setSelectedItemIndexInt(int selectedItemIndexInt) {
        SelectedItemIndex.setText((selectedItemIndexInt + 1) + "");
    }

    public TowarModel getSelectedItem() {
        return getItems().get(getSelectedItemIndexInt());
    }

    public double getSelectedItemVatRateDouble() {
        return getSelectedItem().getStawkaVAT();
    }

    public void setSelectedItemVatRateDouble(Double selectedItemVatRateDouble) {
        VatPrice.setText(selectedItemVatRateDouble.toString());
        getSelectedItem().setStawkaVAT(selectedItemVatRateDouble);
    }
        
    public int getSelectedItemQuantityInt() {
        return getSelectedItem().getIlosc();
    }

    public void setSelectedItemQuantityInt(int selectedItemQuantityInt) {
        Quantity.setText(selectedItemQuantityInt + "");
        getSelectedItem().setIlosc(selectedItemQuantityInt);
    }

    public String getSelectedItemTitleString() {
        return getSelectedItem().getNazwa();
    }

    public void setSelectedItemTitleString(String selectedItemTitleString) {
        Title.setText(selectedItemTitleString);
        getSelectedItem().setNazwa(selectedItemTitleString);
    }

    public Double getSelectedItemPriceDouble() {
        return getSelectedItem().getCenaNetto();
    }

    public void setSelectedItemPriceDouble(Double selectedItemPriceDouble) {
        getSelectedItem().setCenaNetto(selectedItemPriceDouble);
        Price.setText(selectedItemPriceDouble + "");
    }

    public void setSelectedItemPriceDouble(String selectedItemPriceString) {
        setSelectedItemPriceDouble(Double.parseDouble(selectedItemPriceString));
    }
    public void setItemsCount(int count){
        ItemsCount.setText(count + "");
    }
    
    public int getItemsCountInt() {
        return getItems().size();
    }
    
    
    public TowarModel getDefaultTowar() {
        return new TowarModel("", 0.0, 23.0, 1);
    }
    
    
    /**
     * Creates new form WearhouseWindow
     */
    public TowarView() {
        initComponents();

        items = new ArrayList();
        items.add(getDefaultTowar());

        setSelectedItemIndexInt(0);
        refreshView();
    }
    
    public TowarView(ArrayList<TowarModel> towary) {
        initComponents();

        items = towary;
        if (items.isEmpty()){
            items.add(getDefaultTowar());
        }

        setSelectedItemIndexInt(0);
        refreshView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ItemsCount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SelectedItemIndex = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label3 = new javax.swing.JLabel();
        LAbel4 = new javax.swing.JLabel();
        Title = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        PreviousButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        VatPrice = new javax.swing.JTextField();
        LAbel5 = new javax.swing.JLabel();
        LAbel6 = new javax.swing.JLabel();
        Quantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ItemsCount.setText("0");
        ItemsCount.setToolTipText("");

        jLabel2.setText("/");

        SelectedItemIndex.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(SelectedItemIndex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ItemsCount)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ItemsCount)
                    .addComponent(jLabel2)
                    .addComponent(SelectedItemIndex))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Towary");

        Label3.setText("Nazwa Towaru");

        LAbel4.setText("Cena netto");

        Title.setText("jTextField1");

        Price.setText("jTextField2");

        AddButton.setText("Dodaj");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PreviousButton.setText("Poprzedni");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        NextButton.setText("Następny");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Usuń");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Zapisz");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        VatPrice.setText("jTextField2");

        LAbel5.setText("Stawka vat");

        LAbel6.setText("Ilość");

        Quantity.setText("jTextField2");
        Quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PreviousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LAbel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Label3)
                                            .addComponent(LAbel4)
                                            .addComponent(LAbel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(VatPrice)
                                            .addComponent(Price)
                                            .addComponent(Title, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))))))
                        .addGap(85, 85, 85)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label3)
                            .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LAbel4)
                            .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LAbel5)
                            .addComponent(VatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LAbel6)
                            .addComponent(Quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton)
                            .addComponent(DeleteButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PreviousButton)
                            .addComponent(NextButton)
                            .addComponent(SaveButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        getItems().add(getDefaultTowar());
        setSelectedItemIndexInt(getItemsCountInt() - 1);
        refreshView();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        if (getItemsCountInt() == 1){
            return;}
        getItems().remove(getSelectedItem());
        if (getSelectedItemIndexInt() != 0){
            setSelectedItemIndexInt(getSelectedItemIndexInt() - 1);
        }
        refreshView();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void refreshView() {
        setItemsCount(getItemsCountInt());
        setSelectedItemTitleString(getSelectedItemTitleString());
        setSelectedItemPriceDouble(getSelectedItemPriceDouble());
        setSelectedItemVatRateDouble(getSelectedItemVatRateDouble());
        setSelectedItemQuantityInt(getSelectedItemQuantityInt());
    }

    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
        if (getSelectedItemIndexInt() != 0){
            setSelectedItemIndexInt(getSelectedItemIndexInt() - 1);
        }
        refreshView();
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (getSelectedItemIndexInt() != getItemsCountInt() - 1){
            setSelectedItemIndexInt(getSelectedItemIndexInt() + 1);
        }
        refreshView();
    }//GEN-LAST:event_NextButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        setSelectedItemTitleString(Title.getText());
        setSelectedItemPriceDouble(Price.getText());
        setSelectedItemVatRateDouble(Double.parseDouble(VatPrice.getText()));
        setSelectedItemQuantityInt(Integer.parseInt(Quantity.getText()));
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void QuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_QuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TowarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TowarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TowarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TowarView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TowarView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JLabel ItemsCount;
    private javax.swing.JLabel LAbel4;
    private javax.swing.JLabel LAbel5;
    private javax.swing.JLabel LAbel6;
    private javax.swing.JLabel Label3;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JTextField Price;
    private javax.swing.JTextField Quantity;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SelectedItemIndex;
    private javax.swing.JTextField Title;
    private javax.swing.JTextField VatPrice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
