/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Models.TowarModel;
import Models.ZamowienieModel;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author andrz
 */
public class ZamowienieView extends javax.swing.JFrame {
    // <editor-fold defaultstate="collapsed" desc="fields"> 
    private List<ZamowienieModel> zamowienia;
    private DefaultListModel<String> zamowieniaListModel;
    private DefaultListModel<String> TowaryListModel;

    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="geters and seters">  
    public String getNazwa() {
        return NazwaZamowienia.getText();
    }

    public void setNazwa(String Nazwa) {
        NazwaZamowienia.setText(Nazwa);
    }
    
    public int getFilterComboBoxValue() {
        return towaryFilterCombo.getSelectedIndex();
    }

    public void setFilterComboBoxValue(int index) {
        towaryFilterCombo.setSelectedIndex(index);
    }
    
    public String getSearchText() {
        return searchZamowienia.getText();
    }

    public void setSearchText(String Nazwa) {
        searchZamowienia.setText(Nazwa);
    }

    public String getKontrachent() {
        return KontrachentZamowienie.getText();
    }

    public void setKontrachent(String Kontrachent) {
        KontrachentZamowienie.setText(Kontrachent);
    }

    public Integer getPozycjaNaLiscie() {
        return Integer.parseInt(this.PozycjaNaLiscieZamowienie.getText());
    }

    public void setPozycjaNaLiscie(Integer PozycjaNaLiscie) {
        if( PozycjaNaLiscie == null )
            this.PozycjaNaLiscieZamowienie.setText("-1");
        else
            this.PozycjaNaLiscieZamowienie.setText(Integer.toString(PozycjaNaLiscie));
    }
    
    private void setControlsEnabled(boolean enabled) {
        KontrachentZamowienie.setEnabled(enabled);
        NazwaZamowienia.setEnabled(enabled);
        PozycjaNaLiscieZamowienie.setEnabled(enabled);
        SaveZamowienie.setEnabled(enabled);
        jButton3.setEnabled(enabled);
    }
    
    private ZamowienieModel getSelectedZamowienie(){    
        int selectedIndex = ZamowieniaList.getSelectedIndex();
        if (selectedIndex != -1) {
            return zamowienia.get(
               selectedIndex 
            );
        }else{
            return null;
        }
    }// </editor-fold>

    
    /**
     * Creates new form ZamowienieView
     */
    public ZamowienieView() {
        initComponents();
        zamowienia =  new ArrayList<>();
        zamowieniaListModel = new DefaultListModel<>();
        ZamowieniaList.setModel(zamowieniaListModel);
        TowaryListModel = new DefaultListModel<>();
        TowaryList.setModel(TowaryListModel);
        
        handleZamowieniaChange();
        
        ZamowieniaList.addListSelectionListener(getListSelectionListener());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ZamowieniaList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PozycjaNaLiscieZamowienie = new javax.swing.JTextField();
        NazwaZamowienia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        KontrachentZamowienie = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        SaveZamowienie = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TowaryList = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        addZamowienie = new javax.swing.JButton();
        usunZamowienie = new javax.swing.JButton();
        disSelectZamowienie = new javax.swing.JButton();
        towaryFilterCombo = new javax.swing.JComboBox<>();
        searchZamowienia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ZamowieniaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ZamowieniaList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(ZamowieniaList);

        jLabel1.setText("Nazwa:");

        NazwaZamowienia.setToolTipText("");

        jLabel2.setText("Kontrachent:");

        jLabel3.setText("Pozycja na liście:");

        SaveZamowienie.setText("Zapisz");
        SaveZamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveZamowienieActionPerformed(evt);
            }
        });

        jButton3.setText("Zarządzaj Towarami");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        TowaryList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        TowaryList.setEnabled(false);
        jScrollPane2.setViewportView(TowaryList);

        jLabel4.setText("Zamówione Towary:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NazwaZamowienia))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PozycjaNaLiscieZamowienie))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KontrachentZamowienie))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addComponent(SaveZamowienie)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NazwaZamowienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(KontrachentZamowienie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PozycjaNaLiscieZamowienie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveZamowienie)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        addZamowienie.setText("+");
        addZamowienie.setMargin(new java.awt.Insets(5, 5, 5, 5));
        addZamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addZamowienieActionPerformed(evt);
            }
        });

        usunZamowienie.setText("-");
        usunZamowienie.setMargin(new java.awt.Insets(5, 5, 5, 5));
        usunZamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunZamowienieActionPerformed(evt);
            }
        });

        disSelectZamowienie.setText("wyczyść");
        disSelectZamowienie.setToolTipText("");
        disSelectZamowienie.setMargin(new java.awt.Insets(5, 5, 5, 5));
        disSelectZamowienie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disSelectZamowienieActionPerformed(evt);
            }
        });

        towaryFilterCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wszystkie", "Tylko z towarami", "Tylko bez Towarów" }));
        towaryFilterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                towaryFilterComboActionPerformed(evt);
            }
        });

        searchZamowienia.setToolTipText("");
        searchZamowienia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchZamowieniaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchZamowieniaKeyTyped(evt);
            }
        });

        jLabel5.setText("Szukaj");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(towaryFilterCombo, 0, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addZamowienie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(disSelectZamowienie)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(usunZamowienie))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchZamowienia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addZamowienie)
                            .addComponent(usunZamowienie)
                            .addComponent(disSelectZamowienie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(towaryFilterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchZamowienia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addZamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addZamowienieActionPerformed
        createZamowienie();
    }//GEN-LAST:event_addZamowienieActionPerformed

    private void usunZamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunZamowienieActionPerformed
        deleteSelectedZamowienie();
    }//GEN-LAST:event_usunZamowienieActionPerformed

    private void disSelectZamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disSelectZamowienieActionPerformed
        clearSearchCriteria();
        clearForm();
        handleZamowieniaChange();
    }//GEN-LAST:event_disSelectZamowienieActionPerformed

    private void SaveZamowienieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveZamowienieActionPerformed
        saveZamowienie();
    }//GEN-LAST:event_SaveZamowienieActionPerformed

    private void towaryFilterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_towaryFilterComboActionPerformed
        handleZamowieniaChange();
    }//GEN-LAST:event_towaryFilterComboActionPerformed

    private void searchZamowieniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchZamowieniaKeyTyped

    }//GEN-LAST:event_searchZamowieniaKeyTyped

    private void searchZamowieniaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchZamowieniaKeyReleased
        handleZamowieniaChange();
    }//GEN-LAST:event_searchZamowieniaKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        ArrayList<TowarModel> towaryList = getSelectedZamowienie().getListaTowarow();
        TowarView window = new TowarView(towaryList);
        window.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        
        window.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                handleTowaryChange();
            }
        });
        window.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private ListSelectionListener getListSelectionListener(){
        return new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    displayZamowienieDetails();
                }
            }
        };
    }
            
    private void saveZamowienie() {
        ZamowienieModel zamowienie = getSelectedZamowienie();
        if (zamowienie != null) {
            zamowienie.setNazwa(getNazwa());
            zamowienie.setNazwaKontrahenta(getKontrachent());
            zamowienie.setPozycjaNaLiscie(getPozycjaNaLiscie());
            handleZamowieniaChange();
        }
    }
    
    private void deleteSelectedZamowienie() {
        int selectedIndex = ZamowieniaList.getSelectedIndex();
        if (selectedIndex != -1) {
            zamowienia.remove(selectedIndex);
            handleZamowieniaChange();
        }
    }
    
    private void displayZamowienieDetails() {
        displayZamowienieDetails( getSelectedZamowienie());
        setControlsEnabled(true);
        handleTowaryChange();
    }
    
    private void displayZamowienieDetails(ZamowienieModel zamowienie) {
        if(zamowienie != null){
            setNazwa(zamowienie.getNazwa());
            setKontrachent(zamowienie.getNazwaKontrahenta());
            setPozycjaNaLiscie(zamowienie.getPozycjaNaLiscie());
        }
    }
    
    private void displayZamowienieDetails(int index) {
        displayZamowienieDetails(zamowienia.get(index));
    }

    private void createZamowienie() {
        addZamowienieToList("nowy", "", -1);
        ZamowieniaList.setSelectedIndex(zamowieniaListModel.size()-1);
    }

    private void addZamowienieToList(String nazwa, String kontrahent, int pozycja){
        ZamowienieModel zamowienie = new ZamowienieModel(nazwa, kontrahent, pozycja);
        zamowienia.add(zamowienie);
        displayZamowienieDetails(zamowienie);
        handleZamowieniaChange();
    }

    private void handleZamowieniaChange() {
        zamowieniaListModel.clear();
        String searchText = getSearchText();
        int filterType = getFilterComboBoxValue();
        
        for (ZamowienieModel zamowienie : zamowienia) {

            if(!searchText.isEmpty() && !zamowienie.getNazwa().startsWith(searchText)){
                continue;
            }

            switch (filterType) {
                case 1:
                    if(zamowienie.getListaTowarow().isEmpty()){
                        continue;
                    }
                    break;
                case 2:
                    if(!zamowienie.getListaTowarow().isEmpty()){
                        continue;                    
                    }
                    break;
                case 0:
                default:
                    break;
            }

            zamowieniaListModel.addElement(zamowienie.getNazwa());
        }
        clearForm();
        setControlsEnabled(false);
    }

    private void handleTowaryChange() {
        ZamowienieModel zam = getSelectedZamowienie();
        TowaryListModel.clear();
        if(zam != null){
            List<TowarModel> towary = getSelectedZamowienie().getListaTowarow();
            TowaryListModel.clear();
            
            for (TowarModel towar : towary) {
                TowaryListModel.addElement(towar.getNazwa());
            }
        }
    }

    private void clearForm() {
        setNazwa("");
        setKontrachent("");
        setPozycjaNaLiscie(-1);
    }

    private void clearSearchCriteria() {
        setFilterComboBoxValue(0);
        setSearchText("");
        ZamowieniaList.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZamowienieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZamowienieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZamowienieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZamowienieView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZamowienieView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField KontrachentZamowienie;
    private javax.swing.JTextField NazwaZamowienia;
    private javax.swing.JTextField PozycjaNaLiscieZamowienie;
    private javax.swing.JButton SaveZamowienie;
    private javax.swing.JList<String> TowaryList;
    private javax.swing.JList<String> ZamowieniaList;
    private javax.swing.JButton addZamowienie;
    private javax.swing.JButton disSelectZamowienie;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField searchZamowienia;
    private javax.swing.JComboBox<String> towaryFilterCombo;
    private javax.swing.JButton usunZamowienie;
    // End of variables declaration//GEN-END:variables

}
